name = "my-react-worker"
type = "javascript"
main = "worker.js"
account_id = "feb3dd8377172a12b6d69550a5217c91"  # Replace with your actual Cloudflare account ID
workers_dev = true
compatibility_date = "2025-02-18"

[observability.logs]
enabled = true

[site]
bucket = "./build"

[build]
command = "npm run build"

[[kv_namespaces]]
binding = "_my-react-worker-workers_sites_assets"   # The variable you'll use in your Worker script
id = "e867712a91374e779e226f9d0392c380"   # The actual KV namespace ID from Cloudflare dashboard